### ISSUE TITLE
Getting module access error during startup.

### ISSUE THREAD

**Issue by sureshg** [ingokegel/jclasslib#12]
Jclasslib startup on mac throws the following illegal access error even though `java8` is in `PATH` and set as `JAVA_HOME`. 

```
java.lang.IllegalAccessError: class org.gjt.jclasslib.browser.MacEventHandler (in unnamed module @0x318ba8c8) cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @0x318ba8c8
	at org.gjt.jclasslib.browser.MacEventHandler.init(MacEventHandler.kt:14)
	at org.gjt.jclasslib.browser.BrowserApplication.main(Main.kt:45)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-ea/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-ea/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-ea/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-ea/Method.java:535)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)
```
```
OS: Mac OSX Sierra v 10.12
Xcode 8.2.1, Build version 8C1002

java version "1.8.0_111"
JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
```
**Note** -  I do have JDK9 installed, but is not the default JDK.

<img width="1038" alt="screen shot 2017-02-21 at 11 32 30 pm" src="https://cloud.githubusercontent.com/assets/356994/23201463/8738afda-f88e-11e6-817c-7d873a97f96a.png">

**Comment by minsko** [comment]
This issue may have also been fixed by the recent update to MacEventHandler.  A NoClassDefFoundError  was thrown by Java(TM) SE Runtime Environment (build 9+181) not an IllegalAccessError..
