### ISSUE TITLE
java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by liangquandeng** [ingokegel/jclasslib#13]
java.lang.IllegalAccessError: class org.gjt.jclasslib.browser.MacEventHandler (in unnamed module @0x55a1c291) cannot access class com.apple.eawt.Application (in module java.desktop) because module java.desktop does not export com.apple.eawt to unnamed module @0x55a1c291
	at org.gjt.jclasslib.browser.MacEventHandler.init(MacEventHandler.kt:14)
	at org.gjt.jclasslib.browser.BrowserApplication.main(Main.kt:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)

System: macOS Sierra 10.12.3
JDK:  1.8.0_121-b13

**Comment by liangquandeng** [comment]
Sorry , I use JDK9。。。。。。
